apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiga.fullname" . }}-front
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
    app.kubernetes.io/component: taiga-front
spec:
  type: {{ .Values.taigaProtected.service.type }}
  ports:
    - name: http
      targetPort: http
      port: {{ .Values.taigaFront.service.port }}
      protocol: TCP
  selector:
    {{- include "taiga.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: taiga-front
