image:
  repository: quay.io/lknight/docker-wireguard-centos-8-stream
  tag: latest
  pullPolicy: Always

resources:
  requests:
    memory: "50Mi"
    cpu: "10m"
  limits:
    memory: "100Mi"
    cpu: "20m"

env:
  timezone: "America/Denver"
  peers: "1"
  peerdns: "auto"

pvc:
  storageClassName: "default"

serverPort: 51820
#nodeName:
