image:
  repository: quay.io/lknight/docker-wireguard-centos-8-stream
  tag: latest
  pullPolicy: Always

env:
  timezone: "America/Denver"
  peers: "1"
  peerdns: "auto"

pvc:
  storageClassName: "default"

serverPort: 51820
#nodeName:
