apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-modules
  namespace: wireguard
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: "{{ .Values.pvc.storageClassName }}"
