apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-modules
  namespace: wireguard
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  {{ if ne (lower .Values.pvc.storageClassName) "default" }}
  storageClassName: "{{ .Values.pvc.storageClassName }}"
  {{- end }}
