apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config
  namespace: wireguard
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: {{ .Values.pvc.storageClassName }}
