apiVersion: v1
kind: Service
metadata:
  labels:
    app: wireguard
  name: wireguard
  namespace: wireguard
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.serverPort }}
    protocol: UDP
    targetPort: 51820
  selector:
    app: wireguard
